### ISSUE TITLE
Consider adding a setting for going above 100%

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/timechimp-billability-chart#7]
Take for example my recent billability graph:

![image](https://github.com/infi-nl/timechimp-billability-chart/assets/1590536/fe6d2526-f670-4258-a643-2a023fe07abe)

For client work I'm very precise with hours, as invoices get sent for that. But the non-billable part is a bit different, and there are various reasons why I might work something different from my contract hours (40 h/week):

- I work a small bit of overtime (and will likely compensate in another week)
- It might _seem_ like there's some overtime but it might be caused by non-billable hours flowing over into a social event or "borrel" 😄 that I won't write up at all
- Personal circumstances or whatever

So I'd prefer it if the graph would (possibly via a setting) show me:

- Bars that go beyond 100% (and have "100%" be my contract hours for a week
- A horizontal line to emphasize the 100% line
- The % billable be relative to my contract hours

So I might have a week where I worked "110%" but was still spot-on "45% billable" (the 'target' for my current role), instead of "40.9%".

PS. All this assumes that the "Contract Hours" data is available to the extension? If not I might need to be able to add that as a setting too?

**Comment by LucaScorpion** [comment]
Interesting request! Starting with the last point:

> All this assumes that the "Contract Hours" data is available to the extension? If not I might need to be able to add that as a setting too?

This data _can_ be configured in TimeChimp, under HRM > {employee} > Contract or Rooster. ~Another question is if this data is available via the API for non-admin roles.~ This also seems to be available from the `https://app.timechimp.com/api/user/current` endpoint, in the `contractHours` property.

I do think a switch/button to toggle this mode is a good idea, but that should be simple enough. Apart from that I don't see any problems or drawbacks, so I think it's a nice feature to have!

**Comment by LucaScorpion** [comment]
All done, and submitted for review to the Mozilla and Chrome stores!
